include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/gcc-flags.cmake")

set(CMAKE_C_COMPILER gcc-16)
set(CMAKE_CXX_COMPILER g++-16)
set(GCOV_EXECUTABLE "gcov-16" CACHE STRING "GCOV executable" FORCE)

get_filename_component(RPATH "~/.local/lib64" ABSOLUTE)

set(CMAKE_EXE_LINKER_FLAGS
    "-Wl,-rpath,${RPATH}"
    CACHE STRING
    "CMAKE_EXE_LINKER_FLAGS"
    FORCE
)

set(CMAKE_CXX_FLAGS_ASAN
    "${CMAKE_CXX_FLAGS_ASAN} -Wno-maybe-uninitialized"
    CACHE STRING
    "C++ ASAN Flags"
    FORCE
)

# message(NOTICE "USE_VCPKG_TOOLCHAIN: $ENV{USE_VCPKG_TOOLCHAIN}")
# if(DEFINED ENV{USE_VCPKG_TOOLCHAIN} AND NOT "$ENV{USE_VCPKG_TOOLCHAIN}" STREQUAL "")
#   set(USE_VCPKG_TOOLCHAIN $ENV{USE_VCPKG_TOOLCHAIN})
#   message(NOTICE "including USE_VCPKG_TOOLCHAIN: ${USE_VCPKG_TOOLCHAIN}")
#   include("${USE_VCPKG_TOOLCHAIN}")
# endif()
